Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -58,8 +58,50 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     steps:
+      - name: Setup System
+        run: |
+          export DEBIAN_FRONTEND=noninteractive
+          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+          
+          df -h
+          
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+          sudo docker image prune --all --force
+          echo "some directories deleted"
+          rm -rf OP13 || true
+          sudo rm -vrf /home/runner/work/OnePlus_13_KernelSU_SUSFS/OnePlus_13_KernelSU_SUSFS/OP13 || true
+          sudo rm -vrf ~/.cache/bazel/* || true
+          sudo rm -vrf /home/.cache/bazel/* || true
+          sudo rm -vrf /home/runner/.cache/bazel/* || true
+          sudo rm -vrf /home/runner/work/.cache/bazel/* || true
+          sudo rm -vrf /home/runner/work/OnePlus_13_KernelSU_SUSFS/.cache/bazel/* || true
+          sudo rm -vrf /home/runner/work/OnePlus_13_KernelSU_SUSFS/OnePlus_13_KernelSU_SUSFS/.cache/bazel/* || true
+          echo "clean build!?"
+          
+          # Remove large unwanted packages
+          sudo apt-get purge -y \
+            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+          
+          # Regex-based purges (for bulk families like mysql, php, dotnet)
+          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+          
+          # Clean up
+          sudo apt-get autoremove -y
+          sudo apt-get autoclean -y
+          echo "some packages purged"
+          
+          df -h
+
       - name: Parse VERSION input # 解析 VERSION 输入
         run: |
           VERSION=$(echo "${{ github.event.inputs.VERSION }}")
